### ISSUE TITLE
The server responded with a status of 422 (Unprocessable Entity)

### ISSUE THREAD

**Issue by chrism** [ember-cli/ember-twiddle#455]
Hi,

I've been trying to produce an ember-twiddle but every time I add a component i'm no longer able to save the twiddle as a gist.

For example from this twiddle (effectively a brand new one)

https://ember-twiddle.com/1a99a88881f28defaac4727c127a5257

And creating a component (both hbs and js) called `sign-in-header` then pasting

```js
import Ember from 'ember';

export default Ember.Component.extend({
  session: Ember.inject.service(),

  tagName: 'div',
  classNames: ['sign-in-content'],

  actions: {
    gotoMe() {
      this.sendAction();
    }
  }
});
```

appears to always prevent the twiddle from being saved in the future.

no matter what saving as a gist logs to the console

```
PATCH https://api.github.com/gists/1a99a88881f28defaac4727c127a5257 422 (Unprocessable Entity)
Error: The adapter rejected the commit because it was invalid
at new Error (native)
    at Error.t (https://assets.ember-twiddle.com/assets/vendor-2b693411e8f8dfb130561cc53481af0e.js:12:25335)
    at Error.i (https://assets.ember-twiddle.com/assets/vendor-2b693411e8f8dfb130561cc53481af0e.js:81:2858)
    at Error.r (https://assets.ember-twiddle.com/assets/vendor-2b693411e8f8dfb130561cc53481af0e.js:81:3083)
    at r.handleResponse (https://assets.ember-twiddle.com/assets/vendor-2b693411e8f8dfb130561cc53481af0e.js:81:8538)
    at r.c.error (https://assets.ember-twiddle.com/assets/vendor-2b693411e8f8dfb130561cc53481af0e.js:81:9225)
    at c (https://assets.ember-twiddle.com/assets/vendor-2b693411e8f8dfb130561cc53481af0e.js:5:19300)
    at Object.fireWith [as rejectWith] (https://assets.ember-twiddle.com/assets/vendor-2b693411e8f8dfb130561cc53481af0e.js:5:20117)
    at r (https://assets.ember-twiddle.com/assets/vendor-2b693411e8f8dfb130561cc53481af0e.js:7:2143)
    at XMLHttpRequest.t (https://assets.ember-twiddle.com/assets/vendor-2b693411e8f8dfb130561cc53481af0e.js:7:8328)
```

I couldn't find this issue before so have logged it here in the hopes that there may be a solution.

If you need any more details I'd be happy to try to help if I can.

Many thanks

**Comment by bartocc** [comment]
+1 same issue

**Comment by joostdevries** [comment]
Error:
```json
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Gist",
      "code": "custom",
      "field": "contents",
      "message": "contents must have unique filenames"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/gists/#edit-a-gist"
}
```

**Comment by joostdevries** [comment]
Sent request:
```json
{
  "url": "https://api.github.com/gists/8a4ab0152fde2f2910810bc415c62218",
  "description": "New Twiddle",
  "html_url": "https://gist.github.com/8a4ab0152fde2f2910810bc415c62218",
  "created_at": "2016-07-03T15:25:49.000Z",
  "updated_at": "2016-07-03T15:25:49.000Z",
  "owner_login": "joostdevries",
  "public": true,
  "files": {
    "controllers.application.js": {
      "filename": "controllers.application.js",
      "content": "import Ember from 'ember';\n\nexport default Ember.Controller.extend({\n  appName: 'Ember Twiddle'\n});\n",
      "type": "application/javascript"
    },
    "templates.application.hbs": {
      "filename": "templates.application.hbs",
      "content": "<h1>Welcome to {{appName}}</h1>\n<br>\n<br>\n{{outlet}}\n<br>\n<br>",
      "type": "text/plain"
    },
    "twiddle.json": {
      "filename": "twiddle.json",
      "content": "{\n  \"version\": \"0.10.1\",\n  \"EmberENV\": {\n    \"FEATURES\": {}\n  },\n  \"options\": {\n    \"use_pods\": false,\n    \"enable-testing\": false\n  },\n  \"dependencies\": {\n    \"jquery\": \"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js\",\n    \"ember\": \"2.6.0\",\n    \"ember-data\": \"2.6.1\",\n    \"ember-template-compiler\": \"2.6.0\"\n  },\n  \"addons\": {}\n}\n",
      "type": "application/json"
    },
    "controllers.application.js.0": {
      "filename": "controllers.application.js",
      "content": "import Ember from 'ember';\n\nexport default Ember.Controller.extend({\n  appName: 'Ember Twiddle'\n});\n"
    },
    "templates.application.hbs.1": {
      "filename": "templates.application.hbs",
      "content": "<h1>Welcome to {{appName}}</h1>\n<br>\n<br>\n{{outlet}}\n<br>\n<br>"
    },
    "twiddle.json.2": {
      "filename": "twiddle.json",
      "content": "{\n  \"version\": \"0.10.1\",\n  \"EmberENV\": {\n    \"FEATURES\": {}\n  },\n  \"options\": {\n    \"use_pods\": false,\n    \"enable-testing\": false\n  },\n  \"dependencies\": {\n    \"jquery\": \"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js\",\n    \"ember\": \"2.6.0\",\n    \"ember-data\": \"2.6.1\",\n    \"ember-template-compiler\": \"2.6.0\"\n  },\n  \"addons\": {}\n}\n"
    },
    "models.my-model.js.3": {
      "filename": "models.my-model.js",
      "content": "import Model from \"ember-data/model\";\nimport attr from \"ember-data/attr\";\nimport { belongsTo, hasMany } from \"ember-data/relationships\";\n\nexport default Model.extend({\n});\n"
    }
  },
  "history": [
    {
      "id": "6c34018fe2d27447c925bd30471b3004a68fee96",
      "url": "https://api.github.com/gists/8a4ab0152fde2f2910810bc415c62218/6c34018fe2d27447c925bd30471b3004a68fee96",
      "committed_at": "2016-07-03T15:25:49.000Z",
      "history": "8a4ab0152fde2f2910810bc415c62218"
    }
  ]
}
```

**Comment by joostdevries** [comment]
@Gaurav0 looks like the serializer is broken somehow.

**Comment by Gaurav0** [comment]
@chrism @bartocc Can you please verify this is fixed for you on https://canary.ember-twiddle.com ?

**Comment by bartocc** [comment]
it works

**Comment by chrism** [comment]
Hi @Gaurav0 sorry for the slow reply.

It seems to be working fine now — thank you so much for fixing this.
