### ISSUE TITLE
Addons with sass dependency cannot be used

### ISSUE THREAD

**Issue by blimmer** [ember-cli/ember-twiddle#483]
```
ember-twiddle-9f9206a….js:2 version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Installing addon packageInstalling packages for tooling via npmInstalling packages for tooling via npm.Installing packages for tooling via npm..Installing packages for tooling via npm...Installing packages for tooling via npmInstalling packages for tooling via npm.Installing packages for tooling via npm..Installing packages for tooling via npm...Installing packages for tooling via npmInstalling packages for tooling via npm.Installing packages for tooling via npm..Installing packages for tooling via npm...Installing packages for tooling via npmInstalling packages for tooling via npm.Installing packages for tooling via npm..Installing packages for tooling via npm...Installing packages for tooling via npmInstalling packages for tooling via npm.Installing packages for tooling via npm..Installing packages for tooling via npm...Installing packages for tooling via npmInstalled packages for tooling via npm.
installing ember-paper
  create app/styles/app.scss
  install bower packages hammer.js, matchMedia
Installing browser packages via BowerInstalling browser packages via Bower.Installing browser packages via Bower...
  not-cached https://github.com/hammerjs/hammer.js.git#*
  not-cached https://github.com/paulirish/matchMedia.js.git#0.2.0
  resolved https://github.com/paulirish/matchMedia.js.git#0.2.0
  resolved https://github.com/hammerjs/hammer.js.git#2.0.8
Installed browser packages via Bower.
  install package ember-cli-sass
Installing packages for tooling via npm...Installing packages for tooling via npmInstalling packages for tooling via npm.Installing packages for tooling via npm..Installing packages for tooling via npm...Installing packages for tooling via npmInstalling packages for tooling via npm.Installing packages for tooling via npm..Installing packages for tooling via npm...Installing packages for tooling via npmInstalling packages for tooling via npm.Installing packages for tooling via npm..Installing packages for tooling via npm...Installing packages for tooling via npmInstalling packages for tooling via npm.Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.0/linux-x64-47_binding.node
Binary downloaded and installed at /addon-builder/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/linux-x64-47/binding.node
Installing packages for tooling via npm.."/addon-builder/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/linux-x64-47/binding.node" exists. 
 testing binary.
Problem with the binary:
Error: Error relocating /addon-builder/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/linux-x64-47/binding.node: __strtod_internal: symbol not found
Manual build incoming.
Building: /usr/bin/node /addon-builder/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/addon-builder/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@5.7.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/addon-builder/node_modules/which/which.js:14:12)
gyp verb `which` failed     at F (/addon-builder/node_modules/which/which.js:69:19)
gyp verb `which` failed     at E (/addon-builder/node_modules/which/which.js:81:29)
gyp verb `which` failed     at /addon-builder/node_modules/which/which.js:90:16
gyp verb `which` failed     at /addon-builder/node_modules/isexe/index.js:44:5
gyp verb `which` failed     at /addon-builder/node_modules/isexe/access.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 { [Error: not found: python2] code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/addon-builder/node_modules/which/which.js:14:12)
gyp verb `which` failed     at F (/addon-builder/node_modules/which/which.js:69:19)
gyp verb `which` failed     at E (/addon-builder/node_modules/which/which.js:81:29)
gyp verb `which` failed     at /addon-builder/node_modules/which/which.js:90:16
gyp verb `which` failed     at /addon-builder/node_modules/isexe/index.js:44:5
gyp verb `which` failed     at /addon-builder/node_modules/isexe/access.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python { [Error: not found: python] code: 'ENOENT' }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/addon-builder/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:449:14)
gyp ERR! stack     at /addon-builder/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:353:11
gyp ERR! stack     at F (/addon-builder/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (/addon-builder/node_modules/which/which.js:81:29)
gyp ERR! stack     at /addon-builder/node_modules/which/which.js:90:16
gyp ERR! stack     at /addon-builder/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /addon-builder/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.4.10-22.54.amzn1.x86_64
gyp ERR! command "/usr/bin/node" "/addon-builder/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /addon-builder/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
Build failed
node-sass@3.10.0 postinstall: `node scripts/build.js`
Exit status 1
Error: node-sass@3.10.0 postinstall: `node scripts/build.js`
Exit status 1
    at EventEmitter.<anonymous> (/addon-builder/node_modules/npm/lib/utils/lifecycle.js:214:16)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at ChildProcess.<anonymous> (/addon-builder/node_modules/npm/lib/utils/spawn.js:24:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
BuildingBuilding.Building..Building...BuildingBuilding.Building..Building...BuildingBuilding.Building..Building...BuildingBuilt project successfully. Stored in "dist/".
(anonymous function) @ ember-twiddle-9f9206a….js:2n @ vendor-7c44fb7….js:4(anonymous function) @ vendor-7c44fb7….js:4e.(anonymous function) @ vendor-7c44fb7….js:4_takeSafeStep @ vendor-7c44fb7….js:77_takeStep @ vendor-7c44fb7….js:77invoke @ vendor-7c44fb7….js:7flush @ vendor-7c44fb7….js:7flush @ vendor-7c44fb7….js:7end @ vendor-7c44fb7….js:7(anonymous function) @ vendor-7c44fb7….js:7
ember-twiddle-9f9206a….js:2 undefined(anonymous function) @ ember-twiddle-9f9206a….js:2n @ vendor-7c44fb7….js:4(anonymous function) @ vendor-7c44fb7….js:4e.(anonymous function) @ vendor-7c44fb7….js:4_takeSafeStep @ vendor-7c44fb7….js:77_takeStep @ vendor-7c44fb7….js:77invoke @ vendor-7c44fb7….js:7flush @ vendor-7c44fb7….js:7flush @ vendor-7c44fb7….js:7end @ vendor-7c44fb7….js:7(anonymous function) @ vendor-7c44fb7….js:7
```

It seems like the machine that giftwraps external libraries doesn't have `python2` installed on it and causes ember-paper install to fail.

**Comment by Gaurav0** [comment]
Even if we put python2 on it, there's no way to get lib-sass to compile on Alpine Linux, which is why ember-cli-sass fails.

**Comment by blimmer** [comment]
got it - should I close this issue? is it tracked somewhere else?

**Comment by Gaurav0** [comment]
Feel free to leave it open for the next person who asks.

**Comment by blimmer** [comment]
I'll change the title to make it clearer what the issue is - thanks.

**Comment by kybishop** [comment]
For anyone wondering, https://github.com/sass/node-sass/issues/1589 needs to be resolved before progress can be made on this.

**Comment by xomaczar** [comment]
@Gaurav0 - node-sass 4.1.0 now supports alpine linux out of the box. See the above issue for more context.

**Comment by xomaczar** [comment]
@Guarav0 sure - I was just wondering if anything should be done on your side or this is strictly dependency change of my addon - and ember twiddle will just work.

**Comment by Gaurav0** [comment]
@xomaczar I can't be sure till it's tried, but I believe once the necessary tree of dependency bumps takes place, it should just work.

**Comment by xomaczar** [comment]
Nice will give it a try. Keep you posted...

**Comment by xomaczar** [comment]
@Gaurav0 there is a very little information about adding addons to an ember-twiddle. I am trying to figure out if you are guys supporting only npm registry or github, etc - similar to npm?

**Comment by Gaurav0** [comment]
https://canary.ember-twiddle.com/9283452fa01247d967705c25e599cc82?openFiles=templates.application.hbs%2C
