### ISSUE TITLE
Integration tests fail

### ISSUE THREAD

**Issue by dfalling** [ember-cli/ember-twiddle#508]
New Ember Twiddles don't seem to be able to run integration tests.  They always fail with this error:
```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.create (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.0/ember.debug.js:52996:36)
    at Object.create (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.0/ember.debug.js:13365:24)
    at instantiate 
```

Caused by this line: `this.render(hbs`{{input}}`);`

Is this a known issue or is there something else I can do to fix it?  Thanks!

**Comment by Gaurav0** [comment]
Fixed on canary. See #500

**Comment by dfalling** [comment]
That's it, thanks!
