### ISSUE TITLE
Mirage does not work if ember-changeset is a dependency

### ISSUE THREAD

**Issue by williamhaley** [ember-cli/ember-twiddle#533]
I have a [sample Twiddle](https://ember-twiddle.com/298765fd3acccb3df45c590836c3fd9b?openFiles=twiddle.json%2C) that uses mirage to fake out some API data. This works as you'd expect. Mocked data is returned from mirage

For reasons I can't quite figure out, it breaks if I add `ember-changeset` as a dependency.

You can see the bug by using the Twiddle above and adding the following to the `addons` section of `twiddle.json`.

```
    "ember-changeset": "1.2.2"
```

This error appears. It looks like a `CORS` issue, but I'm not sure why adding `ember-changeset` would cause it.

```
OPTIONS https://ember-twiddle.com/dogs 403 ()
send @ VM396 jquery.js:9664
ajax @ VM396 jquery.js:9215
_ajaxRequest @ VM398 ember-data.js:14377
(anonymous) @ VM398 ember-data.js:14367
initializePromise @ VM397 ember.debug.js:58221
Promise @ VM397 ember.debug.js:58706
ajax @ VM398 ember-data.js:14350
findAll @ VM398 ember-data.js:13863
_findAll @ VM398 ember-data.js:11552
_fetchAll @ VM398 ember-data.js:10210
findAll @ VM398 ember-data.js:10180
model @ VM403 about:srcdoc:67
deserialize @ VM397 ember.debug.js:25949
applyHook @ VM397 ember.debug.js:55711
runSharedModelHook @ VM397 ember.debug.js:56309
getModel @ VM397 ember.debug.js:56508
(anonymous) @ VM397 ember.debug.js:55565
tryCatch @ VM397 ember.debug.js:58173
invokeCallback @ VM397 ember.debug.js:58185
publish @ VM397 ember.debug.js:58156
(anonymous) @ VM397 ember.debug.js:37639
invoke @ VM397 ember.debug.js:339
flush @ VM397 ember.debug.js:407
flush @ VM397 ember.debug.js:531
end @ VM397 ember.debug.js:601
run @ VM397 ember.debug.js:724
join @ VM397 ember.debug.js:746
run.join @ VM397 ember.debug.js:21562
(anonymous) @ VM397 ember.debug.js:21625
fire @ VM396 jquery.js:3148
fireWith @ VM396 jquery.js:3260
ready @ VM396 jquery.js:3472
completed @ VM396 jquery.js:3503
VM394 about:srcdoc:1 XMLHttpRequest cannot load https://ember-twiddle.com/dogs. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 403.
VM397 ember.debug.js:27784 Error while processing route: index Ember Data Request GET /dogs returned a 404
Payload (Empty Content-Type)
 Error
    at AdapterError (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.11.0/ember-data.js:12676:16)
    at Class.handleResponse (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.11.0/ember-data.js:14291:14)
    at ajaxError (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.11.0/ember-data.js:14789:25)
    at Class.hash.error (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.11.0/ember-data.js:14363:23)
    at fire (https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js:3148:30)
    at Object.fireWith [as rejectWith] (https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js:3260:7)
    at done (https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js:9316:14)
    at XMLHttpRequest.callback (https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js:9718:8)
logError @ VM397 ember.debug.js:27784
error @ VM397 ember.debug.js:27725
triggerEvent @ VM397 ember.debug.js:27882
trigger @ VM397 ember.debug.js:55580
trigger @ VM397 ember.debug.js:56098
(anonymous) @ VM397 ember.debug.js:55906
tryCatch @ VM397 ember.debug.js:58173
invokeCallback @ VM397 ember.debug.js:58185
publish @ VM397 ember.debug.js:58156
publishRejection @ VM397 ember.debug.js:58099
(anonymous) @ VM397 ember.debug.js:37639
invoke @ VM397 ember.debug.js:339
flush @ VM397 ember.debug.js:407
flush @ VM397 ember.debug.js:531
end @ VM397 ember.debug.js:601
run @ VM397 ember.debug.js:724
join @ VM397 ember.debug.js:746
run.join @ VM397 ember.debug.js:21562
hash.error @ VM398 ember-data.js:14364
fire @ VM396 jquery.js:3148
fireWith @ VM396 jquery.js:3260
done @ VM396 jquery.js:9316
callback @ VM396 jquery.js:9718
VM397 ember.debug.js:16911 Ember Data Request GET /dogs returned a 404
Payload (Empty Content-Type)

Error
    at AdapterError (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.11.0/ember-data.js:12676:16)
    at Class.handleResponse (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.11.0/ember-data.js:14291:14)
    at ajaxError (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.11.0/ember-data.js:14789:25)
    at Class.hash.error (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.11.0/ember-data.js:14363:23)
    at fire (https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js:3148:30)
    at Object.fireWith [as rejectWith] (https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js:3260:7)
    at done (https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js:9316:14)
    at XMLHttpRequest.callback (https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js:9718:8)
```

I repeated the same behavior in a standard ember app on my host machine and the same problem does not exist. Seems to only happen when using twiddle.

**Comment by Gaurav0** [comment]
This was issue #522. This was fixed in canary when reported. I have published the fix to production as of this morning.

**Comment by williamhaley** [comment]
Thanks!
