### ISSUE TITLE
Upgrade Ember to 2.18 LTS

### ISSUE THREAD

**Issue by lukesargeant** [ember-cli/ember-twiddle#582]
Hey guys, I recently tried to run the project locally, but got dependency errors so ember wouldn't serve or run tests on both master and on the PR with the UX redesign (does anyone else have this problem?)

So... rather than face my problems, I tried to upgrade the project to 2.18.

WIP: https://github.com/lukesargeant/ember-twiddle/tree/ember_cli_2_18

I hit issues when I removed bower with the sass dependency. I've not worked with sass in ember before as always used LESS so I don't know whether there is an easy fix for this.

My question is whether it's better to fix the current master (assuming it's broken for everyone) before starting to upgrade Ember, or whether upgrading is a valid next step given the problem.

**Comment by lukesargeant** [comment]
For reference, here's the log when I try to run master:

```
$ ember s
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
bootstrap-sassy config: some JS loaded [dropdown,collapse], glyphicons enabled
bootstrap-sassy config: some JS loaded [dropdown,collapse], glyphicons enabled
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy: `function () {
            return __dirname;
          }`.
Build Canceled: Broccoli Builder ran into an error with `Babel` plugin. 💥
The plugin {"_parallelBabel":{"requireFile":"/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/ember-cli-htmlbars-inline-precompile/lib/require-from-worker","buildUsing":"build","params":{"templateCompilerPath":"/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/ember-source/dist/ember-template-compiler.js","parallelConfig":[]}}} didn't export a Plugin instance
TypeError: The plugin {"_parallelBabel":{"requireFile":"/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/ember-cli-htmlbars-inline-precompile/lib/require-from-worker","buildUsing":"build","params":{"templateCompilerPath":"/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/ember-source/dist/ember-template-compiler.js","parallelConfig":[]}}} didn't export a Plugin instance
    at PluginManager.validate (/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/broccoli-babel-transpiler/index.js:107:21)
    at Babel.processString (/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/broccoli-babel-transpiler/index.js:206:25)
    at Promise.then.result.output (/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/sargeal/Documents/Projects/twiddle/ember-twiddle/node_modules/rsvp/dist/rsvp.js:1039:33)
```

**Comment by Gaurav0** [comment]
In my experience, due to the way we mimic private Ember-cli apis, it is considerably easier to update ember-cli one version at a time.

**Comment by Gaurav0** [comment]
Your stacktrace seems to indicate you have Babel 6 installed. master is still on Babel 5.

**Comment by lukesargeant** [comment]
@Gaurav0 thanks for that, I'll try to take another look later.

**Comment by Gaurav0** [comment]
Update: You should be able to run locally now.
